version: '3.12'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"

  web:
    build: .
    ports:
      - "5002:5002"
    depends_on:
      - db
